version: '3'

services:
  # Database
  db:
    container_name: mysql5.7
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: estore
      # MYSQL_USER: db_user
      # MYSQL_PASSWORD: 1234
    networks:
      - multiserver
  # phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - multiserver
  # PHP7.3
  php7.3:
    container_name: php7.3
    depends_on:
      - db
    # image: php:7.3-apache
    image: usmana/php:7.3
    # build:
    #   context: ./
    #   dockerfile: ./Dockerfile.php7.3
    ports:
      - '8073:80'
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - multiserver
  # PHP5.6
  php5.6:
    container_name: php5.6
    depends_on:
      - db
    # image: php:5.6-apache
    image: usmana/php:5.6
    # build:
    #   context: ./
    #   dockerfile: ./Dockerfile.php5.6
    ports:
      - '8056:80'
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - multiserver
networks:
  multiserver:
# Named volumes must be listed under the top-level volumes key, as shown.
# volumes:
#   db_data: